[gcp_service_account]
type = "service_account"
project_id = "streamlit-app-467511"
private_key_id = "2b7a769d58577402b5feca5d8ef2d7d92bc6214c"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIY8bIQeD1XP9I
oNNXCWWd3OmsDHF7O306nGwNG3VlLc84idq/BWXA1iJIMO6TMZO/uQe/Foatv3Zz
x17Jb/ATRxMELCVgJy6hvyhfiDbPaaKW7y675XwGiYZc/BEC+3RfBd2UWmaKpaD7
IEDzh6z8VyTLl+4NuKxczgqpuKw7ZNRU6hLYqB2KrSa/y9eiZUWM785GyzAXtjQn
wElNQscUht0ApxKF+to7IC1Bp2ztAbMc4hKXc42cwbu/hO9MzEdYTuOW7qkABwre
nRDH6KSoDMkFC4yGN/FXa7SQ/9NnKXP15f+4jV5yF3bRkmGH2GyFWT7yXyJhLASM
KO1nMHfvAgMBAAECggEAEWgZX4VzDqoCKUNPGF0vAB3gbmfmTT4UDEzqIqyJiT07
DHFtGIq8SM2EMzrAGCkf6T3skYmM/JEh4oy+8kbqI8KL9FQHxLWimoo9ISjdgGBv
4llRRe3fob6KEJAUw9DAtKbELwIE39l86+0Xt0L7bWMxRXFWssc7GBSnXt01ZZme
ztwXZAkFYX84VS9CUCGWrSpmjToh/BR7JBzTHNCz/20kLmk5q8pdDrJvjVzdgXxt
07F3QDp4p36gthOgdJpZF7du3GRDeXBWm0vLuCn4n1gs422txj54WJorU1lbTrHD
DvO6ogTjbcLcLqWjt4KbsaLMItJeN5yWu/ahncoVAQKBgQDsjEEHUPz2SgE9Ggcj
B2A//GrIDbT58uq2n10iUhHljZx9pfT3Ii9N8QjlK32SMpbD0/FJNZpT5iapBViz
QjdOgwIo/TOE/3E4ldCfRMgWjXpcBx75uns56HPs0MDmtKDXxybCLdjRWOyOR/bh
FWAYGcJ3bfO0CzNW3R9PLDA1dwKBgQDY3lS5ydgz3+gyaETfOklbPd86Hbb8BCBa
5dpD504OaxdlKpsB1nJc+GC/9xka1pt107Fo5G7qMQahQ/qVLX7qNNOOZREOO46f
09fIrp4AX8CkvEMA/db4TXhATsj8c8fZBUk+ALnGQHUlVwQnydJEi1Cn5OaQR4bt
VcshRPrPSQKBgB4VjGOw0itEqDmsKMI0uvIIWVBOJfkwAtftFrw5sdr/EqsMQ0Z3
C4sfH6F90X+ZfYE0YFiOP61x9PLEIk7SGhSbJtgts7KzhiPLMfg/mC7+GVTA9xiN
tgRcYvn4ZsAwstAenPhPOmcNpzBFSMnBnTITfJ8R1c/NKN9gSg4YsZzrAoGAAc2v
hLACBURqaOjnEbgpXgHgtloC6IucPUVGEGR/CK2pTyUQju5amx1RqKcEZW29czhk
dEvaBEaOGI85KT5snMP9smRyxNyH7hpT5A5XsAcb0gLix8JUpFH4mwhMsZTA57Qc
jNByuwxULRBRL4eFIR7Ld+n2ZOLDY3vgKZGqSEkCgYEA4GAIANdccQ+ujdTlPiIJ
7v88+b3lyMLClJ8NddVlROhfBwYIiYPWVYz2zs5xv6OPz2LXGRoMzKNVitRecDJi
Zsj3of95+kEVzcxNy6xxuC40w2/J1pMB8wDuj+kcAcSjWi8CJauHXbAaDJ3gi++J
IoK2pzRTRXYif8L3hd9HY9M=
-----END PRIVATE KEY-----
'''
client_email = "mosto-app@streamlit-app-467511.iam.gserviceaccount.com"
client_id = "107484392691033626464"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mosto-app%40streamlit-app-467511.iam.gserviceaccount.com"
universe_domain = "googleapis.com"